# Generated by Django 6.0.4 on 2026-05-03 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        ('motor_adaptativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(default=0)),
                ('nota', models.FloatField(default=1.0, help_text='Calificación en escala 1.0 a 5.0')),
                ('total_preguntas', models.IntegerField()),
                ('correctas', models.IntegerField(default=0)),
                ('completado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='examenes.examen')),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='motor_adaptativo.sesionexamen')),
            ],
            options={
                'db_table': 'resultados',
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, default='', max_length=200)),
                ('pregunta', models.TextField()),
                ('respuesta_correcta', models.TextField()),
                ('respuesta_incorrecta', models.TextField(blank=True, default='')),
                ('tiempo_por_pregunta', models.IntegerField(help_text='Tiempo en segundos')),
                ('dificultad', models.IntegerField()),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='analitica.resultado')),
            ],
            options={
                'db_table': 'respuestas_estudiante',
            },
        ),
    ]
