# Generated by Django 6.0.4 on 2026-05-03 21:44

import apps.examenes.models.curso
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('codigo', models.CharField(default=apps.examenes.models.curso.generar_codigo, max_length=8, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=200)),
                ('tiempo', models.IntegerField(help_text='Duración total en minutos')),
                ('num_preguntas', models.IntegerField(help_text='Mínimo de preguntas. En modo fijo es el total exacto')),
                ('retroalimentacion', models.BooleanField(default=False)),
                ('dificultad_inicial', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Medio'), (3, 'Difícil')], default=2)),
                ('max_intentos', models.IntegerField(default=1, help_text='Número de intentos permitidos. 0 = ilimitado')),
                ('es_guiado', models.BooleanField(default=False, help_text='Si True, el agente genera una explicación antes de cada pregunta')),
                ('modo', models.CharField(choices=[('fijo', 'Fijo'), ('maestria', 'Maestría')], default='fijo', help_text='Fijo: termina en num_preguntas. Maestría: termina cuando el estudiante domina los conceptos', max_length=10)),
                ('max_preguntas', models.IntegerField(default=20, help_text='Solo en modo maestría. Tope máximo para evitar examen infinito')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='examenes.curso')),
            ],
            options={
                'db_table': 'examenes',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='examenes.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inscripciones',
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
