# Generated by Django 6.0.4 on 2026-05-03 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptos', models.JSONField(default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_conocimiento', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_conocimiento', to='examenes.examen')),
            ],
            options={
                'db_table': 'modelos_conocimiento',
                'unique_together': {('estudiante', 'examen')},
            },
        ),
        migrations.CreateModel(
            name='SesionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField(default=1)),
                ('dificultad_actual', models.IntegerField(default=2)),
                ('preguntas_respondidas', models.IntegerField(default=0)),
                ('pregunta_actual', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado')], default='en_progreso', max_length=20)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='examenes.examen')),
            ],
            options={
                'db_table': 'sesiones_examen',
                'unique_together': {('estudiante', 'examen', 'intento')},
            },
        ),
    ]
